"""Generate the candidate reference document.

The catalog knows what candidates *exist*; the tuning logs know what they
*did*. Neither alone answers the question you actually have in front of a
regression -- "is this candidate supposed to be able to run here, and has it
ever won anything?" -- so this joins them into one table.

Deliberately a separate script rather than a `bigcherry` subcommand: it reads
tuning logs, which are evidence from particular runs on particular hardware,
not build inputs. Nothing in the build depends on it.

Usage:

    python tools/candidate_report.py

Reads the newest manifest under artifacts/, every ``*.log`` under
artifacts/tuning-logs/, and writes docs/reference/CANDIDATES.md.

Log file names carry their own provenance and are parsed for it:

    gfx1100gre-rdna3-s3f15.log   -> arch gfx1100gre, screen 3, final 15
    gfx1030-rdna2-s1f1.log       -> arch gfx1030,    screen 1, final 1
    gfx1030-rdna2-native.log     -> native mode, no tuning

Sample counts matter for reading the table and are printed with it: a column
taken at one sample per candidate says almost nothing about which candidate is
faster, only that the plumbing selected one.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path


def _repository_root() -> Path:
    """Find the repository root without coupling analysis to folder depth."""
    for candidate in Path(__file__).resolve().parents:
        if (candidate / "config" / "recipes.toml").is_file() and (
            candidate / "tools" / "bigcherry"
        ).is_dir():
            return candidate
    raise RuntimeError("cannot locate BigCherry repository root")


ROOT = _repository_root()
ARTIFACTS = ROOT / "artifacts"
LOG_DIR = ARTIFACTS / "tuning-logs"
OUT = ROOT / "docs" / "reference" / "CANDIDATES.md"

WINNER_RE = re.compile(r"winner ([A-Za-z0-9_:.\-]+) \(([0-9.]+)%")
LOGNAME_RE = re.compile(
    r"^(?P<arch>[a-z0-9]+)-(?P<family>rdna\d)"
    r"(?:-s(?P<screen>\d+)f(?P<final>\d+)|-native)"
    r"(?P<suffix>-[a-z]+)?\.log$"
)


def newest_manifest() -> Path:
    """The manifest from the most recently generated revision directory."""
    candidates = sorted(
        ARTIFACTS.glob("*/hip-autotune-manifest.json"), key=lambda p: p.stat().st_mtime
    )
    if not candidates:
        raise SystemExit("no manifest under artifacts/; run `bigcherry generate` first")
    return candidates[-1]


class LogRun:
    """One tuning run: where it ran, how carefully, and what won."""

    def __init__(self, path: Path):
        self.path = path
        m = LOGNAME_RE.match(path.name)
        if not m:
            raise SystemExit(f"cannot parse provenance from log name: {path.name}")
        self.arch = m.group("arch")
        self.arch_family = m.group("family")
        self.screen = m.group("screen")
        self.final = m.group("final")
        self.suffix = (m.group("suffix") or "").lstrip("-")
        self.native_only = self.screen is None

        self.wins: dict[str, int] = defaultdict(int)
        self.improvements: dict[str, list[float]] = defaultdict(list)
        text = path.read_text(encoding="utf-8", errors="replace")
        for name, pct in WINNER_RE.findall(text):
            self.wins[name] += 1
            self.improvements[name].append(float(pct))
        self.tuned = text.count("bigcherry: tuned")
        # test-backend-ops prints one ERR line per failing case.
        self.err_lines = len(re.findall(r"^\[MUL_MAT\] ERR =", text, re.M))

    @property
    def label(self) -> str:
        if self.native_only:
            return f"{self.arch} (native)"
        tag = f"{self.arch} {self.screen}/{self.final}"
        return f"{tag} {self.suffix}" if self.suffix else tag

    @property
    def trustworthy(self) -> bool:
        """Can this run's numbers support a claim about which candidate is faster?

        One sample cannot separate a 1% difference from noise, so those columns
        are presented as evidence that a path was exercised, not that it won.
        """
        return not self.native_only and int(self.final) >= 10


def median(values: list[float]) -> float:
    ordered = sorted(values)
    return ordered[len(ordered) // 2]


def main() -> None:
    manifest = json.loads(newest_manifest().read_text(encoding="utf-8"))
    runs = [LogRun(p) for p in sorted(LOG_DIR.glob("*.log"))]
    tuned_runs = [r for r in runs if not r.native_only]

    by_family: dict[str, list[dict]] = defaultdict(list)
    for cand in manifest["candidates"]:
        by_family[cand["family"]].append(cand)

    ever_won = {name for r in runs for name in r.wins}

    out: list[str] = []
    w = out.append

    w("# Candidate reference")
    w("")
    w("Generated by `python tools/candidate_report.py`. Do not edit by hand --")
    w("regenerate it, and add analysis to the plan items under `docs/planning/` instead.")
    w("")
    w(
        f"Manifest `{manifest['manifest_hash']}`, variant set "
        f"`{manifest['variant_set']}`, upstream `{manifest['source_revision'][:12]}`."
    )
    w("")

    w("## How to read this")
    w("")
    w("A candidate existing means the catalog enumerated it. It does **not** mean")
    w("it can run on your GPU, and it does not mean it has ever been measured.")
    w("Three separate things, and conflating them is how this project has")
    w("repeatedly fooled itself:")
    w("")
    w("- **Generated** -- in the manifest below.")
    w("- **Runnable here** -- `architecture_mask` admits the GPU *and* the")
    w("  family's `can_execute` accepts the signature. An `mmf:f32` candidate is")
    w("  generated on every build and runnable on none of this project's GPUs.")
    w("- **Measured** -- actually timed. A candidate can be eligible on every")
    w("  signature and never win one.")
    w("")

    w("## Runs behind the numbers")
    w("")
    w(
        "| Run | Mode | Screen/final samples | Signatures tuned | Failing cases | Trust |"
    )
    w("| --- | --- | --- | --- | --- | --- |")
    for r in runs:
        mode = "native" if r.native_only else "tune"
        samples = "--" if r.native_only else f"{r.screen}/{r.final}"
        trust = (
            "timing"
            if r.trustworthy
            else ("correctness only" if not r.native_only else "baseline")
        )
        w(
            f"| `{r.path.name}` | {mode} | {samples} | {r.tuned} | {r.err_lines} | {trust} |"
        )
    w("")
    w("**Only runs marked `timing` may be used to argue one candidate is faster")
    w("than another.** A `1/1` run resolves nothing below roughly 10%; it is")
    w("included because it still proves a path was reachable and produced a")
    w("correct result.")
    w("")

    w("## Summary by family")
    w("")
    w("| Family | Candidates | Source classes | Ever won |")
    w("| --- | --- | --- | --- |")
    for family in sorted(by_family):
        cands = by_family[family]
        classes = sorted({c["source_class"] for c in cands})
        won = sum(1 for c in cands if c["stable_name"] in ever_won)
        w(f"| {family} | {len(cands)} | {', '.join(classes)} | {won} |")
    w(f"| **total** | **{len(manifest['candidates'])}** | | **{len(ever_won)}** |")
    w("")

    w("## Candidates that have won at least once")
    w("")
    w("Sorted by total wins across all tuning runs.")
    w("")
    header = "| Candidate | Family | " + " | ".join(r.label for r in tuned_runs) + " |"
    w(header)
    w("| --- | --- | " + " | ".join("---" for _ in tuned_runs) + " |")

    family_of = {c["stable_name"]: c["family"] for c in manifest["candidates"]}
    totals = {n: sum(r.wins.get(n, 0) for r in tuned_runs) for n in ever_won}
    for name in sorted(ever_won, key=lambda n: (-totals[n], n)):
        cells = []
        for r in tuned_runs:
            n = r.wins.get(name, 0)
            if n and r.trustworthy:
                cells.append(f"{n} ({median(r.improvements[name]):.1f}%)")
            elif n:
                cells.append(str(n))
            else:
                cells.append("--")
        w(f"| `{name}` | {family_of.get(name, '?')} | " + " | ".join(cells) + " |")
    w("")
    w("Cells show wins, and for `timing` runs the median improvement over native.")
    w("A `--` means that candidate won nothing in that run; it says nothing about")
    w("whether it was eligible.")
    w("")

    w("## Full inventory")
    w("")
    for family in sorted(by_family):
        cands = sorted(by_family[family], key=lambda c: c["stable_name"])
        w(f"### {family} ({len(cands)})")
        w("")
        w("| Candidate | Source class | Architectures | Config |")
        w("| --- | --- | --- | --- |")
        for c in cands:
            archs = c["architectures"]
            if len(archs) > 4:
                arch_text = f"{len(archs)} archs"
            else:
                arch_text = ", ".join(archs) or "none"
            cfg = ", ".join(f"{k}={v}" for k, v in sorted(c["config"].items()))
            star = " ⭐" if c["stable_name"] in ever_won else ""
            w(
                f"| `{c['stable_name']}`{star} | {c['source_class']} | "
                f"{arch_text} | {cfg or '--'} |"
            )
        w("")

    w("A star marks a candidate that has won at least one signature somewhere.")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    print(
        f"  {len(manifest['candidates'])} candidates, {len(ever_won)} have won, "
        f"{len(runs)} runs"
    )


if __name__ == "__main__":
    main()
