#!/usr/bin/env python3
"""Write an assembly file of stubs for the libr4d symbols libr3 does not build yet (run before libr3 links).

libr4d's row table names every kernel entry point. A unit on exclude.txt is not compiled, so its entry points are
undefined and the plugin would not load. Each undefined libr4d symbol gets a stub here that returns
RAD_E_UNSUPPORTED (-18), all in one section between r3_stub_begin and r3_stub_end; r3_registry.cpp leaves out every
row whose launch points into that section.

Only symbols that are libr4d's are stubbed (their names contain "r4d"); an undefined symbol of anything else is a
real link error and is left to the loader to report.

Usage: r3_gen_stubs.py <nm> <out.S> <object>...
"""
from __future__ import annotations

import subprocess
import sys


def symbols(nm: str, objects: list[str], flag: str) -> set[str]:
    out = subprocess.run([nm, flag, "--format=posix", *objects], capture_output=True, text=True, check=True).stdout
    names = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and not line.endswith(":"):
            names.add(parts[0])
    return names


def main() -> int:
    nm, out_path, objects = sys.argv[1], sys.argv[2], sys.argv[3:]
    undefined = symbols(nm, objects, "--undefined-only") - symbols(nm, objects, "--defined-only")
    stubs = sorted(name for name in undefined if "r4d" in name.lower())
    lines = [
        "/* generated by r3_gen_stubs.py: entry points of libr4d units libr3 does not build yet */",
        '        .section .text.r3_stubs,"ax",@progbits',
        "        .globl r3_stub_begin",
        "r3_stub_begin:",
    ]
    for name in stubs:
        lines += [f"        .globl {name}", f"        .type {name},@function", f"{name}:",
                  "        movl $-18, %eax", "        ret"]
    lines += ["        .globl r3_stub_end", "r3_stub_end:", "        nop",
              '        .section .note.GNU-stack,"",@progbits', ""]
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"r3_gen_stubs: {len(stubs)} libr4d symbol(s) stubbed, {len(undefined) - len(stubs)} other undefined left to the linker")
    return 0


if __name__ == "__main__":
    sys.exit(main())
