"""HI67 slice 2a: deterministic tensor init for CPU-reference correctness evidence.

The HI67 correctness contract (RV49, adjudicated by GPT again in RV77 for the
slice 2/3 implementation) compares a candidate's GPU output C against a
CPU-reference result R, and native's own GPU output N against that SAME R:

    E_N = NMSE(R, N)
    E_C = NMSE(R, C)
    E_C <= E_N + correctness_headroom_fraction * (T - E_N)

R comes from test-backend-ops' own CPU-vs-backend comparison. Producing N and
C requires two SEPARATE process invocations (GGML_HIP_FORCE_CANDIDATE=native,
then GGML_HIP_FORCE_CANDIDATE=<candidate>) -- the comparison is only valid if
both processes generated the exact same input tensors, so both are actually
being compared against the same R.

Confirmed via source read (2026-08-20) that this does not hold today:
init_tensor_uniform() seeds a `std::default_random_engine` from
`std::random_device{}()` -- genuinely different per process -- and splits the
work across N_THREADS parallel tasks with no per-thread-substream determinism
either. Two invocations of the same test case get different random tensors.

This patch adds an opt-in deterministic mode, gated by an env var so every
existing caller (upstream's own test suite, BigCherry's other tune-mode
corpus runs) is byte-for-byte unchanged when it is unset:

- BIGCHERRY_TEST_DETERMINISTIC_SEED=<nonzero uint64>: init_tensor_uniform()
  switches to a single-threaded, seeded std::default_random_engine. A
  monotonic call counter (reset per process, incremented once per
  init_tensor_uniform call) is folded into the per-call seed, so repeated
  calls within one process (one per tensor operand in a test case) get
  distinct but still fully reproducible sequences -- two independent
  processes running the identical test case in the identical operand order
  reach identical call indices and therefore identical tensors.
- The generated float buffer's FNV-1a digest is printed on stderr as a
  machine-parseable `BIGCHERRY_REF_DIGEST` line, so a Python driver can
  assert two invocations (forced-native, forced-candidate) actually compared
  against the same input without needing to capture and diff the full tensor.

Scope: only init_tensor_uniform(), the initializer test_mul_mat (the op
family HI67's correctness contract is about) actually uses. init_tensor_
kq_mask()/init_tensor_tril() (attention/triangular-matrix tests, unrelated to
MUL_MAT candidate dispatch) have the same std::random_device non-determinism
but are out of scope for this patch -- tracked as follow-up if a future HI67
slice needs CPU-reference evidence for a non-MUL_MAT op family.
"""

GROUP = "core"
# Verified offline: dry-run apply + idempotence against the real vendored
# checkout (both edits apply cleanly, re-applying is a no-op, brace count
# delta matches the block being replaced). NOT yet compiled or run on real
# hardware -- no C++ toolchain is available in this environment. Promote to
# "validated" once a real build exercises BIGCHERRY_TEST_DETERMINISTIC_SEED
# and confirms two independent processes emit matching BIGCHERRY_REF_DIGEST
# lines for the same seed.
STATE = "untested"

from bigcherry.patcher import Edit, FilePatch

_HELPERS = '''
// bigcherry (HI67 slice 2a): deterministic tensor init for CPU-reference
// correctness evidence. See patches/1222_hi67_deterministic_test_backend_ops_seed/patch.py
// for the full rationale. Opt-in via BIGCHERRY_TEST_DETERMINISTIC_SEED -- unset
// (the default) leaves every existing caller byte-for-byte unchanged.
static uint64_t bigcherry_deterministic_seed() {
    static const uint64_t seed = [] () -> uint64_t {
        const char * env = getenv("BIGCHERRY_TEST_DETERMINISTIC_SEED");
        return env ? strtoull(env, nullptr, 10) : 0;
    }();
    return seed;
}

static bool bigcherry_deterministic_mode() {
    return bigcherry_deterministic_seed() != 0;
}

// Monotonic per-process call index. Two independent processes running the
// identical test case in the identical operand order reach identical
// indices, which is what makes a forced-native and a forced-candidate
// invocation's tensors reproducible from the same base seed.
static uint64_t bigcherry_next_call_index() {
    static std::atomic<uint64_t> counter{0};
    return counter.fetch_add(1, std::memory_order_relaxed);
}

// FNV-1a. Not cryptographic -- only used to let two independent processes
// prove they generated byte-identical tensor data for the same call index.
static uint64_t bigcherry_fnv1a(const void * data, size_t nbytes) {
    uint64_t h = 14695981039346656037ull;
    const uint8_t * p = (const uint8_t *) data;
    for (size_t i = 0; i < nbytes; i++) {
        h ^= p[i];
        h *= 1099511628211ull;
    }
    return h;
}

'''

_BRANCH = '''    size_t nels = ggml_nelements(tensor);
    std::vector<float> data(nels);
    if (bigcherry_deterministic_mode()) {
        // bigcherry (HI67 slice 2a): single-threaded, seeded generator --
        // reproducible across independent processes given the same base
        // seed and call order. See patches/1222_hi67_deterministic_test_backend_ops_seed/patch.py.
        const uint64_t call_index = bigcherry_next_call_index();
        const uint64_t call_seed = bigcherry_deterministic_seed()
            ^ (call_index * 0x9E3779B97F4A7C15ull);
        std::default_random_engine gen(static_cast<unsigned>(call_seed));
        std::uniform_real_distribution<float> distribution(min, max);
        for (size_t i = 0; i < nels; i++) {
            data[i] = distribution(gen);
        }
        const uint64_t digest = bigcherry_fnv1a(data.data(), data.size() * sizeof(float));
        fprintf(stderr, "BIGCHERRY_REF_DIGEST name=%s call_index=%llu digest=%016llx nels=%zu\\n",
                ggml_get_name(tensor), (unsigned long long) call_index,
                (unsigned long long) digest, nels);
    } else {
        // parallel initialization
        static const size_t n_threads = N_THREADS;

        auto init_thread = [&](size_t start, size_t end) {
            thread_local std::default_random_engine gen(std::random_device{}());
            std::uniform_real_distribution<float> distribution(min, max);
            for (size_t i = start; i < end; i++) {
                data[i] = distribution(gen);
            }
        };

        if (n_threads == 1) {
            init_thread(0, nels);
        } else {
            std::vector<std::future<void>> tasks;
            tasks.reserve(n_threads);
            for (size_t i = 0; i < n_threads; i++) {
                size_t start =     i*nels/n_threads;
                size_t end   = (i+1)*nels/n_threads;
                tasks.push_back(std::async(std::launch::async, init_thread, start, end));
            }
            for (auto & t : tasks) {
                t.get();
            }
        }
    }'''

_ORIGINAL_BLOCK = '''    size_t nels = ggml_nelements(tensor);
    std::vector<float> data(nels);
    {
        // parallel initialization
        static const size_t n_threads = N_THREADS;

        auto init_thread = [&](size_t start, size_t end) {
            thread_local std::default_random_engine gen(std::random_device{}());
            std::uniform_real_distribution<float> distribution(min, max);
            for (size_t i = start; i < end; i++) {
                data[i] = distribution(gen);
            }
        };

        if (n_threads == 1) {
            init_thread(0, nels);
        } else {
            std::vector<std::future<void>> tasks;
            tasks.reserve(n_threads);
            for (size_t i = 0; i < n_threads; i++) {
                size_t start =     i*nels/n_threads;
                size_t end   = (i+1)*nels/n_threads;
                tasks.push_back(std::async(std::launch::async, init_thread, start, end));
            }
            for (auto & t : tasks) {
                t.get();
            }
        }
    }'''

import re as _re

# The noise-stripped copy the patcher anchors against blanks comment text to
# spaces (same length, same newlines) rather than removing it, so the "//
# parallel initialization" comment line inside the block must be matched as
# "any non-newline content", not its literal text.
_ANCHOR = _re.escape(_ORIGINAL_BLOCK).replace(
    _re.escape("        // parallel initialization\n"),
    r"[^\n]*\n",
)
assert _ANCHOR != _re.escape(_ORIGINAL_BLOCK), "comment placeholder substitution did not match"

PATCH = FilePatch(
    path="tests/test-backend-ops.cpp",
    description="add an opt-in deterministic seed mode to init_tensor_uniform() so two "
                "independent test-backend-ops invocations (forced-native, forced-candidate) "
                "can be proven to compare against the same CPU-reference input (HI67 slice 2a)",
    edits=(
        Edit(
            id="hi67-deterministic-helpers",
            anchor=r"^static void init_tensor_uniform\(ggml_tensor \* tensor, float min = -1\.0f, float max = 1\.0f\) \{$",
            mode="insert_before",
            rationale="right before init_tensor_uniform's own definition, so the helpers "
                       "it depends on are declared first",
            text=_HELPERS,
            guard=r"bigcherry \(HI67 slice 2a\): deterministic tensor init",
        ),
        Edit(
            id="hi67-deterministic-branch",
            anchor=_ANCHOR,
            mode="replace",
            rationale="init_tensor_uniform's parallel-random-init block -- the only "
                       "std::random_device use in the initializer test_mul_mat relies on",
            text=_BRANCH,
            guard=r"bigcherry \(HI67 slice 2a\): single-threaded, seeded generator",
            max_span_lines=40,
        ),
    ),
)

PATCHES = [PATCH]
