#!/bin/bash
# MET01 1337/1338 recheck: build once, then NCMOE={8,20,41} x cache={0,2048,8192} x 3 repeats.
# Each matrix process serves one request so the trace-gated 1337 hit/miss/upload counters are request-scoped.
# Fusion is disabled for every matrix arm; compare greedy md5 before interpreting throughput.
# Upstream limits: one target device, no pipeline parallelism. MTP sidecar is a separate context/device.
# Usage: queue-moe-cache.sh <tag>
# Env: RUN_OVERRIDE, BC_MODEL, LONG_TOKENS, N_PREDICT.
set -u
TAG=${1:?tag}
cd "$(cd "$(dirname "$0")/../../.." && pwd)"
R=/mnt/data/bigcherry-work/runs
export BC_HIP_PATH=/mnt/vault/tmp/bc-rocm
export BC_MODEL=${BC_MODEL:-/mnt/data/llm-models/qwen3.8-flash-next/gguf/mtp/Qwen3.8-Flash-Next-UD-IQ4_XS-00001-of-00003.gguf}
docker stop radiance-vllm >/dev/null 2>&1

RUN=${RUN_OVERRIDE:-b-moe-cache-$TAG}
N=moe-cache-$TAG
jobs=$(mktemp)
[ -n "${RUN_OVERRIDE:-}" ] || echo "VIS=0,1,2,3 BUILD $RUN bigcherry:stock:linux-multi moe-cache-profile gfx1100,gfx1201,gfx1030" > "$jobs"
cat > "$R/$N.arms.sh" <<'ARMS'
#!/bin/bash
# generated by queue-moe-cache.sh: <llama-server> <out-root>
set -euo pipefail
for n in 8 20 41; do
  env ARMS=matrix MTP=1 GPU=2 NCMOE=$n CACHE_MIB="0 2048 8192" REPEATS=3 \
    LONG_TOKENS=${LONG_TOKENS:-4096} N_PREDICT=${N_PREDICT:-512} \
    bash tools/lab/flash-next/moe-copy-ab.sh "$1" "$2/ncmoe-$n"
done
ARMS
chmod +x "$R/$N.arms.sh"
echo "VIS=0,1,2,3 SCRIPT $N $R/$N.arms.sh @$RUN $R/$N" >> "$jobs"
bash tools/lab/plan-qualification/queue.sh "$jobs"
rc=$?
echo "QUEUE_EXIT=$rc $(date -Is)"
rm -f "$jobs"

grep -E "^C(0|2048|8192)-r[123]-(short|long) (short|long):|patch=1337_moe_expert_caching|identity across cache|^  (short|long):|SERVER_FAILED|BUILD_FAILED" "$R/$N.log" | cut -c1-320
echo "matrix: NCMOE=8,20,41 cacheMiB=0,2048,8192 repeats=3 fusion=disabled"
echo ALL_RUNS_DONE
exit $rc
