#!/bin/bash
# MET01 / 1337 / 1338: real Flash-Next MoE-cache qualification on host-resident experts.
# Builds experiment moe-cache-profile, then runs one R9700 target plus the production MTP sidecar:
# C0 = --n-cpu-moe N, no cache; C4096 = same + --moe-cache-mib 4096;
# R = optional profile-record arm when PROFILE is unset; P4096 = same cache with BIGCHERRY_MOE_CACHE_PROFILE;
# C0b = repeated no-cache control. Reports prefill/decode t/s, MTP acceptance and greedy md5 per request/arm.
# Usage: queue-moe-cache.sh <tag>
# Env: NCMOE (41), PROFILE (optional held-out STRP profile), RUN_OVERRIDE, BC_MODEL, LONG_TOKENS, N_PREDICT.
set -u
TAG=${1:?tag}
cd "$(cd "$(dirname "$0")/../../.." && pwd)"
R=/mnt/data/bigcherry-work/runs
export BC_HIP_PATH=/mnt/vault/tmp/bc-rocm
export BC_MODEL=${BC_MODEL:-/mnt/data/llm-models/qwen3.8-flash-next/gguf/mtp/Qwen3.8-Flash-Next-UD-IQ4_XS-00001-of-00003.gguf}
docker stop radiance-vllm >/dev/null 2>&1

RUN=${RUN_OVERRIDE:-b-moe-cache-$TAG}
N=moe-cache-$TAG
jobs=$(mktemp)
[ -n "${RUN_OVERRIDE:-}" ] || echo "VIS=0,1,2,3 BUILD $RUN bigcherry:stock:linux-multi moe-cache-profile gfx1100,gfx1201,gfx1030" > "$jobs"
cat > "$R/$N.arms.sh" <<'ARMS'
#!/bin/bash
# generated by queue-moe-cache.sh: <llama-server> <out-root>
env ARMS=qualify MTP=1 GPU=2 NCMOE=${NCMOE:-41} CACHE_MIB=4096 \
  PROFILE="${PROFILE:-}" LONG_TOKENS=${LONG_TOKENS:-4096} N_PREDICT=${N_PREDICT:-512} \
  bash tools/lab/flash-next/moe-copy-ab.sh "$1" "$2"
ARMS
echo "VIS=0,1,2,3 SCRIPT $N $R/$N.arms.sh @$RUN $R/$N" >> "$jobs"
bash tools/lab/plan-qualification/queue.sh "$jobs"
rc=$?
echo "QUEUE_EXIT=$rc $(date -Is)"
rm -f "$jobs"

grep -E "^(C0|C0b|C4096|P4096|R) (short|long)|^identity across arms|^per request:|^  (short|long)|SERVER_FAILED|BUILD_FAILED" "$R/$N.log" | cut -c1-280
echo "profile source: ${PROFILE:-generated by R arm from the same request sequence}"
echo ALL_RUNS_DONE
exit $rc
